config/routes.rb
  Rails.application.routes.draw do

  resources :owners
  resources :tenants
  resources :categories
  resources :marketings
  resources :steps
  resources :letters do
       post 'basic_letter', on: :collection
       post 'cover_letter', on: :collection
       post 'proposal_purchase', on: :collection
       post 'proposal_lease', on: :collection
       post 'exclusive_agreement', on: :collection
       post 'beechwood_letter', on: :collection
     end
  resources :notifications do
       get 'just_user', on: :collection
       get 'all_users', on: :collection
     end
  resources :invoices
  resources :maps do
     post "place", on: :collection
     get "places", on: :collection
  end

  resources :appointments
  resources :searcheds
  resources :canvas

  resources :addresses do
      get 'autocomplete', on: :collection
    end

  resources :mainposts
  resources :comments
  resources :likes

  root to: 'visitors#index'
  match "about" => "pages#about", as: :about, via: :get


  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { registrations: 'registrations', confirmations: 'confirmations'}
    resources :personal_messages, only: [:create, :new]
    resources :conversations, only: [:index, :show]
    resources :users

    resources :groups do
      get 'autocomplete', on: :collection
    end

    resources :tasks
    resources :companies
    resources :events do
    get 'destroy_all', on: :collection
    end

    resources :recurring_events
    resources :projects do
       get 'resources', on: :collection
       get 'description', on: :collection
       get 'budget', on: :collection
       get 'requirements', on: :collection
       get 'projected_start_time', on: :collection
       get 'actual_finshed_time', on: :collection
       get 'development', on: :collection
       get 'maintenance', on: :collection
       get 'technology', on: :collection
       get 'business', on: :collection
       get 'autocomplete', on: :collection
    end

    resources :touches
    resources :leads
    resources :deals do
      resources :posts
      resources :issues
      resources :comments
      get 'autocomplete', on: :collection
    end

    match "users/settheme" => "users#set_theme", as: :set_theme, via: :get
    match "users/sharegroups" => "users#sharegroups", as: :sharegroups, via: :post
    match "search" => "search#create", as: :searches, via: [:get, :post]
    match "search/prepare" => "search#prepare", as: :prepareshearch, via: :get
    match "/dashboard/searchcontacts/" => "dashboard#contacts_search", as: :dash_contacts_search, via: :get
    match "touches/contact/:id" => "touches#contact", as: :contact_touches, via: [:get, :post]

    get '/dashboard', to: 'dashboard#index'

    resources :properties do
     get 'category', on: :collection
     get 'search', on: :collection
     resources :posts
     resources :issues
     get 'autocomplete', on: :collection
    end

    resources :contacts do
      get 'autocomplete', on: :collection
      get 'searchname', on: :collection
      post 'inport', on: :collection
      get 'letter'=> 'contacts#letter'
    end

  end

app/models/search.rb
class Search < ApplicationRecord
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
   before_action :authenticate_user!
def create
     if params[:query].present?
      query =  params[:query].split.map(&:capitalize).join(' ')
       @contacts = Contact.search(query).order('first_name ASC').page(params[:page])
      respond_to do |format|
        format.html
        format.js
      end

    end
  end
  def prepare
    prepared_contacts = Contact.all
    prepared_contacts.each do  |contact|
      if contact.first_name && contact.last_name
        name = contact.first_name + ' ' + contact.last_name
        contact.update_attribute(:name, name)
      end
    end
    redirect_to contacts_path
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_groups.html.erb
<div class="card card-5 mt-4" >
  <div class="card-header card-header-icon b-bottom pb-3 mt-4 pt-3">
    <div class="card-icon bg-dark  ml-2">
      <i class="material-icons">group</i>
    </div>
    <div class="pt-3">
      <%= link_to 'Groups ','/groups/', class: "text-info mt-4"%> | <%= link_to '+ Contact', new_contact_path, class: "text-info  mt-4", remote: true %>
    </div>
  </div>
  <div class="card-body">
    <div class="list-group border-0 pt-0  mt-0">
      <% user_contact = current_user.contacts %>
      <% active = params[:group_id] == nil || params[:group_id].empty? && !session[:selected_group_id] ? 'bg-dark' : '' %>
      <%= link_to contacts_path, class: "list-group-item text-info #{active}", remote: true do %>
          All Contacts <span class="badge text-info"><%= user_contact.count %></span>
      <% end %>

      <% @groups.each do |group| %>
        <% active = params[:group_id].to_i == group.id || (session[:selected_group_id] && session[:selected_group_id].to_i == group.id) ? 'bg-dark' : ''  %>
          <%= link_to contacts_path(group_id: group.id ), class: "list-group-item text-info #{active}", remote: true do %>
            <%= group.name %><span class="badge text-info "><%= group.contacts.count %></span>
          <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/search/_index.html.erb
<div id="main-c-wrap">
<div class="container-fluid pt-0" >
   <div class="row pt-0">
      <div class="col-md-3 group-sidenav" id="sidenav"><%= render 'layouts/sidenav' %>
      </div>
      <div class="col-md-9   ">
         <div class="card card-5 mt-4 pt-0">
            <div class="card-header card-header-icon r-padding-card">
               <span>
                  <H3 class="pl-3 pb-4 text-hudson">
                     Contacts<a data-toggle="modal" data-target="#myModal" class="" title="">&nbsp;<i class="fa fa-file-excel-o text-info"></i></a>
                     <div class="pull-right">
                        <a  class="mb-4" id="sort_contacts" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="material-icons">view_module</i>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="sort_contacts">
                           <div class="card">
                              <article class="card-body">
                                 <h4 class="card-title mb-4 mt-1">Sort Into Sub Group</h4>
                                 <p>
                                 </p>
                                 <hr>
                                 <ul class="list-group" id="list-county">
                                    <li class="list-group-item">
                                       <%= link_to "Westchester", contacts_path(:group_id => params[:group_id], :county => "Westchester "), class: " text-info send-county" %>
                                    </li>
                                    <li class="list-group-item">
                                       <%= link_to "Dutchess", contacts_path(:group_id => params[:group_id] , :county => "Dutchess"), class: "text-info send-county" %>
                                    </li>
                                    <li class="list-group-item">
                                       <%= link_to "Ulster", contacts_path(:group_id => params[:group_id], :county => "Ulster "), class: " text-info send-county" %>
                                    </li>
                                    <li class="list-group-item">
                                       <%= link_to "Orange", contacts_path(:group_id => params[:group_id], :county => "Orange "), class: " text-info send-county"%>
                                    </li>
                                    <li class="list-group-item">    <%= link_to "Rockland", contacts_path(:group_id => params[:group_id], :county => "Rockland "), class: " text-info send-county"%>
                                    </li>
                                 </ul>
                              </article>
                           </div>
                        </div>
                     </div>
                  </H3>
               </span>
               <div class="hide-form">
                  <div class="col-md-12 small-search-form-container ">
                     <%= form_for(@search, remote: true, authenticity_token: true, class: 'form-inline ') do |f| %>
                     <span class=" small-search-form-container  span-out">
                        <ul class="list-inline-custom small-search-form-container ">
                           <li class="list-inline-item-custom">
                              <div class="long-input-div">
                                 <%= text_field_tag :query, params[:query], class: "form-control  text-white", placeholder: "Name", id: "r-search" %>
                              </div>
                           </li>
                           <li class="list-inline-item-custom">
                              <div class="small-input-div">
                                 <button type="submit" class="btn btn-outline-info btn-round btn-just-icon " id="send-search">
                                    <i class="material-icons">search</i>
                                    <div class="ripple-container"></div>
                                 </button>
                              </div>
                           </li>
                     </span>
                     </ul>
                     <% end %>
                  </div>
               </div>
            </div>
            <div class="panel panel-default mt-3 card-5 main-contact-panel">
               <table class="table" id="contacts"><%= render  @contacts %>
               </table>
               <% if @contacts.blank? %>
               <div class="panel-footer message">
                  <div class="alert alert-warning">
                     <strong>Record not found</strong>
                  </div>
                  <% end %>
               </div>
               <div class="text-center p-3" id="pagin">
                  <nav><%= paginate @contacts, remote: true %>
                  </nav>
               </div>
               <div class="modal fade" id="form-modal"  >
                  <div class="container">
                     <div class="col-md-9 mr-auto ml-auto">
                        <div class="modal-body" id="form-modal-body"></div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</div>
<!-- Modal -->
<%= render 'modalcsv' %>
</div>

app/views/search/_modalcsv.html.erb
<div id="myModal" class="modal fade  bd-example-modal-lg  modal-size-xl" role="dialog">
<div class="modal-dialog  modal-size-xl" >
<div class="modal-content modal-size-xl card-6">
<div class="modal-header b-bottom pb-4">
   <button type="button" class="close" data-dismiss="modal">&times;</button>
   <h4 class="modal-title text-left text-light">Import CSV for Contacts</h4>
</div>
<div class="modal-body b-bottom">
   <%= form_tag inport_contacts_path, multipart: true do %>
   <div class="row" style="width 100% !important;">
      <div class="col-md-12 text-white mb-4">
         <label class=" text-white ml-2" >Choose file<small>(required)</small></label>
         <div class="fileinput fileinput-new input-group pt-3" data-provides="fileinput">
            <span class="input-group-addon btn bg-hudson text-white btn-file ml-2"><span class="fileinput-new">Select file</span><span class="fileinput-exists">Change</span> <%= file_field_tag :file %></span>
            <a href="#" class="input-group-addon btn btn-danger fileinput-exists" data-dismiss="fileinput">Remove</a>
            <br> <br>
            <div class="col-md-12 ">
               <div class="form-control ml-0 text-white" data-trigger="fileinput"><i class="fa fa-file fileinput-exists"></i> <span class="fileinput-filename"></span></div>
            </div>
         </div>
      </div>
   </div>
   <div class="col-md-12">
      <% Group.all.each.each_slice(4) do |group| %>
      <div class="col-md-12 mb-3">
         <div class="row">
            <% group.each do |group| %>
            <div class="col-md-3">
               <div class="togglebutton p-2">
                  <label>
                  <input type="checkbox" name="group_id[]"  value=
                     <%="#{group.id}" if group.id %> class="users-for-new-group"/>
                  <span class="toggle"></span>
                  <span class="text-white"><%= group.name %>
                  </span>
                  </label>
               </div>
            </div>
            <% end %>
         </div>
       <hr class="bg-light">
      </div>
      <% end %>
   </div>
   <div class="col-md-12">

      <% User.all.each.each_slice(6) do |user| %>
      <div class="col-md-12">
         <div class="row">
            <% user.each do |user| %>
            <%  next if !user.first_name  %>
            <div class="col-md-2">
               <div class="togglebutton ">
                  <label>
                  <input type="checkbox" name="input[]" checked="true" value=
                     <%="#{user.id}" if user.first_name %> class="users-for-new-group"/>
                  <span class="toggle"></span>
                  <span class="text-white"><%= user.first_name if user.first_name %>
                  </span>
                  </label>
               </div>
            </div>
            <% end %>
         </div>
      </div>
      <% end %>
   </div>
   <div class="modal-footer b-top">
      <hr>
      <%= submit_tag "Import CSV", class: "btn bg-hudson" %>
   </div>
   <% end %>
</div>

app/views/search/_share_form.js.erb
$('#form-modal-body').html('<%= j render("form", ajax_true: true) %>' );
$('.select_g_picker').selectpicker('val', '<%= @groups.to_s %>').selectpicker('setStyle', 'btn-outline-info');
$('.select_u_picker').selectpicker('val', '<%= @users.to_s %>').selectpicker('setStyle', 'btn-outline-info');
$('#form-modal').modal('show')

app/views/search/_show.html.erb
   <%= render 'show_form' %>

<div class="card-body  first-show-card" >
   <div class="panel panel-default first-show-card">
      <div class="panel-heading">
      </div>
      <div class="panel-body col-md-12 first-show-card">
         <ul id="contact-info list-group first-show-card">
            <li class="list-group-item text-muted text-left" contenteditable="false">Profile</li>
            <li class=" profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Name</strong></span><span class="float-right c-info-text-right"><%= @contact.name if @contact.name %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Phone: </strong></span><span class="float-right c-info-text-right"><%= @contact.phone if  @contact.phone %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Cell Phone: </strong></span><span class="float-right c-info-text-right"><%= @contact.cell if  @contact.cell %></span></li>
            <li class=" profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Address: </strong></span><span class="float-right c-info-text-rightt"><%= @contact.address if  @contact.address %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Email: </strong></span><span class="float-right c-info-text-right"><%= @contact.email if @contact.email %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Company: </strong></span><span class="float-right c-info-text-right"><%= @contact.company if @contact.company %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Web Address</strong></span> <span class="float-right c-info-text-right"> <%= @contact.web_address  if  @contact.web_address  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Owns or Rents</strong></span> <span class="float-right c-info-text-right"> <%= @contact.owns_cents  if  @contact.owns_cents  %></span></li>
            <li class="profile-list  list-group-item"><span class="pull-left"><strong class="left-c-text">Prefix</strong></span> <span class="float-right c-info-text-right"> <%= @contact.prefix  if  @contact.prefix  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">First Name</strong></span> <span class="float-right c-info-text-right"> <%= @contact.first_name  if  @contact.first_name  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Middle Name</strong></span> <span class="float-right c-info-text-right"> <%= @contact.middle_name  if  @contact.middle_name  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Last Name</strong></span> <span class="float-right c-info-text-right"> <%= @contact.last_name  if  @contact.last_name  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Suffix</strong></span> <span class="float-right c-info-text-right"> <%= @contact.suffix  if  @contact.suffix  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Position</strong></span> <span class="float-right c-info-text-right"> <%= @contact.postion  if  @contact.first_name  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Latitude</strong></span> <span class="float-right c-info-text-right"> <%= @contact.latitude  if  @contact.latitude  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Longitude</strong></span> <span class="float-right c-info-text-right"> <%= @contact.longitude  if  @contact.longitude  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Type</strong></span> <span class="float-right c-info-text-right"> <%= @contact.type  if  @contact.type  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Facility Size</strong></span> <span class="float-right c-info-text-right"> <%= @contact.facility_size  if  @contact.facility_size  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Total Number Of Employees</strong></span> <span class="float-right c-info-text-right"> <%= @contact.total_number_of_employees  if  @contact.total_number_of_employees  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Sic</strong></span> <span class="float-right c-info-text-right"> <%= @contact.sic  if  @contact.sic  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Primary Industry</strong></span> <span class="float-right c-info-text-right"> <%= @contact.primary_industry  if  @contact.primary_industry  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Year Of Founding</strong></span> <span class="float-right c-info-text-right"> <%= @contact.year_of_Founding  if  @contact.year_of_Founding  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Created</strong></span> <span class="float-right c-info-text-right"> <%= @contact.created_at.strftime("%d %b. %Y")   if  @contact.created_at  %></span></li>
            <li class=" profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Last contacted</strong></span> <span class="float-right c-info-text-right"> </span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Street Number: </strong></span><span class="float-right c-info-text-right"><%= @contact.street_num if @contact.street_num  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Street Name: </strong></span><span class="float-right c-info-text-right"><%= @contact.strret_name if @contact.strret_name  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">County: </strong></span><span class="float-right c-info-text-right"><%= @contact.county if @contact.county  %></span></li>
            <li class="profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Country: </strong></span><span class="float-right c-info-text-right"><%= @contact.country if @contact.country %></span></li>
            <li class=" profile-list list-group-item"><span class="pull-left"><strong class="left-c-text">Postal_code: </strong></span><span class="float-right c-info-text-right"><%= @contact.postal_code if @contact.postal_code %></span></li>
            <li class="profile-list  list-group-item"><span class="pull-left"><strong class="left-c-text">City: </strong></span><span class="float-right c-info-text-right"><%= @contact.city if @contact.city%></span></li>
         </ul>
      </div>
   </div>
</div>
</div>
</div>
<div class="col-md-4">
   <div class="card card-profile card-5">
      <div class="card-avatar">
         <a href="">
         <%= image_tag @contact.avatar.present? ? @contact.avatar.url(:thumb) : 'https://placehold.it/150x150', class: "media-object" %>
         </a>
      </div>
      <div class="card-body">
         <h6 class="card-category text-gray"> <%= @contact.company  if @contact.company  %></h6>
         <h4 class="card-title"> <%= @contact.first_name if @contact.last_name  %> <%= @contact.first_name if @contact.last_name  %> </h4>
         <p class="card-description">
            <%= @contact.address if @contact.address%>
         </p>

         <button type="button" class="btn-back btn bg-hudson btn-round text-white">Go Back</button>




      </div>
   </div>
   <div class="list-group">
      <a href="#" class="list-group-item bg-black">
      </a>
   </div>
   <div class="card card-5 p-3 irst-show-card">
      <div class="card-header first-show-card">
         <h5>Contact Basic Info <span>     <%= link_to edit_contact_path(@contact.id), class: "text-info pull-right", title: 'edit', rel: "tooltip"  do %>
      <i class=" fa fa-edit e-contact"></i>
      <% end %></span></h5>
      </div>
      <ul class="list-group">
         <li class="profile-list list-group-item"><span class="pull-left "><strong class="">First Name</strong></span> <span class="float-right"> <%= @contact.first_name  if  @contact.first_name  %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Middle Name</strong></span> <span class="float-right"> <%= @contact.middle_name  if  @contact.middle_name  %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Last Name</strong></span> <span class="float-right"> <%= @contact.last_name  if  @contact.last_name  %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Position</strong></span> <span class="float-right"> <%= @contact.postion  if  @contact.first_name  %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Web Address</strong></span> <span class="float-right"> <%= @contact.web_address  if  @contact.web_address  %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Phone: </strong></span><span class="float-right"><%= @contact.phone if  @contact.phone %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Cell: </strong></span><span class="float-right"><%= @contact.cell if  @contact.cell %></span></li>
         <li class="profile-list list-group-item"><span class="pull-left"><strong class="pr-2">Email: </strong></span><span class="float-right"><%= @contact.email if @contact.email %></span></li>
      </ul>
   </div>
   <div class="card card-5 p-4 bg-black rounded-0" style="background-color: black !important;">
      <div class="card-header bg-black rounded-0">
         <h2>Contact Notes</h2>
      </div>
      <div class="card-body bg-black">
         <p><%= @contact.notes %></p>
      </div>
   </div>
   <div class="card card-5 p-4 bg-black rounded-0">
      <div class="card-header p-0 bg-black rounded-0">
         <div class="row">
            <div class="col-md-5">
               <h4>Contact Touches</h4>
         </div>
          <div class="col-md-7">
            <span class="pull-right"> <%= link_to  contact_touches_path(@contact.id), class: 'text-danger' do %>
                View <%= @contact.name %> touches
            <% end %>
            </span>
         </div>
         </div>

      </div>
      <% if @contact.contact_touches %>
      <% @contact.contact_touches.each do |touch| %>
      <p>
         <% if touch.email %>
         <strong>Email:</strong>
         <%= touch.email %>
         <% end %>
      </p>
      <% if touch.phone %>
      <p>
         <strong>Phone:</strong>
         <%= touch.phone %>
      </p>
      <% end %>
      <% if touch.postcard %>
      <p>
         <strong>Postcard:</strong>
         <%= touch.postcard %>
      </p>
      <% end %>
      <% if touch.social_media %>
      <p>
         <strong>Social media:</strong>
         <%= touch.social_media %>
      </p>
      <% end %>
      <% if touch.in_person %>
      <p>
         <strong>In person:</strong>
         <%= touch.in_person %>
      </p>
      <% end %>
      <% if touch.letter %>
      <p>
         <strong>Letter:</strong>
         <%= touch.letter %>
      </p>
      <% end %>
      <% if touch.description %>
      <p>
         <strong>Description:</strong>
         <%= touch.description %>
      </p>
      <% end %>



      <span> <%= link_to 'Edit', edit_touch_path(touch), class: 'text-success' %>

      </span>
      <hr>
      <% end %>
      <% end %>
      <div class="row">
         <div class="col-md-6">
             <%= link_to 'All touches', touches_path, class: 'text-info' %>
          </div>
          <div class="col-md-6">
             <%= link_to 'New Touch', new_touch_path, class: 'text-info pull-right pt-1' %>
          </div>
      </div>

   </div>
</div>
</div>
</div>

app/views/search/_table.js.erb
$('#contacts').html('<%= escape_javascript render(@contacts) %>');
$('#pagin').html('<%= escape_javascript paginate(@contacts, remote: true) %>');
$('#sidenav').html('<%= escape_javascript render("layouts/sidenav") %>');

app/views/search/create.js.erb
$('#main-content').html('<%= escape_javascript render("contacts/index") %>');
<%= render 'table.js.erb' %>

app/views/search/index.js.erb
$('#main-content').html('<%= escape_javascript render("contacts/index") %>');
<%= render 'table.js.erb' %>

app/views/search/new.html.erb
  <div class="contacts-outer">
    <div class="container-fluid">
      <div class="row">

        <div class="col-xl-12 mt-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <strong class="">New Contact</strong>
            </div><%= render 'plan_form' %>
          </div>
        </div>
      </div>
    </div>
  </div>

app/views/search/show.js.erb
$('#main-c-wrap').html('<%= escape_javascript render("show") %>');