config/routes.rb
  Rails.application.routes.draw do

  resources :owners
  resources :tenants
  resources :categories
  resources :marketings
  resources :steps
  resources :letters do
       post 'basic_letter', on: :collection
       post 'cover_letter', on: :collection
       post 'proposal_purchase', on: :collection
       post 'proposal_lease', on: :collection
       post 'exclusive_agreement', on: :collection
       post 'beechwood_letter', on: :collection
     end
  resources :notifications do
       get 'just_user', on: :collection
       get 'all_users', on: :collection
     end
  resources :invoices
  resources :maps do
     post "place", on: :collection
     get "places", on: :collection
  end

  resources :appointments
  resources :searcheds
  resources :canvas

  resources :addresses do
      get 'autocomplete', on: :collection
    end

  resources :mainposts
  resources :comments
  resources :likes

  root to: 'visitors#index'
  match "about" => "pages#about", as: :about, via: :get


  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { registrations: 'registrations', confirmations: 'confirmations'}
    resources :personal_messages, only: [:create, :new]
    resources :conversations, only: [:index, :show]
    resources :users

    resources :groups do
      get 'autocomplete', on: :collection
    end

    resources :tasks
    resources :companies
    resources :events do
    get 'destroy_all', on: :collection
    end

    resources :recurring_events
    resources :projects do
       get 'resources', on: :collection
       get 'description', on: :collection
       get 'budget', on: :collection
       get 'requirements', on: :collection
       get 'projected_start_time', on: :collection
       get 'actual_finshed_time', on: :collection
       get 'development', on: :collection
       get 'maintenance', on: :collection
       get 'technology', on: :collection
       get 'business', on: :collection
       get 'autocomplete', on: :collection
    end

    resources :touches
    resources :leads
    resources :deals do
      resources :posts
      resources :issues
      resources :comments
      get 'autocomplete', on: :collection
    end

    match "users/settheme" => "users#set_theme", as: :set_theme, via: :get
    match "users/sharegroups" => "users#sharegroups", as: :sharegroups, via: :post
    match "search" => "search#create", as: :searches, via: [:get, :post]
    match "search/prepare" => "search#prepare", as: :prepareshearch, via: :get
    match "/dashboard/searchcontacts/" => "dashboard#contacts_search", as: :dash_contacts_search, via: :get
    match "touches/contact/:id" => "touches#contact", as: :contact_touches, via: [:get, :post]

    get '/dashboard', to: 'dashboard#index'

    resources :properties do
     get 'category', on: :collection
     get 'search', on: :collection
     resources :posts
     resources :issues
     get 'autocomplete', on: :collection
    end

    resources :contacts do
      get 'autocomplete', on: :collection
      get 'searchname', on: :collection
      post 'inport', on: :collection
      get 'letter'=> 'contacts#letter'
    end

  end

app/models/notification.rb
class Notification < ApplicationRecord
    has_and_belongs_to_many :users
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]

  # GET /notifications
  # GET /notifications.json
  def index
    @notifications = Notification.all
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end
  def just_user
      current_user.notifications.each do |notification|
      notification.destroy
    end
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'All your notifications where successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def all_users
    @notifications = Notification.all
    @notifications.each do |notification|
      notification.destroy
    end
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: "Everyone's notifications where successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notification_params
      params.require(:notification).permit(:name, :thing, :thing_id,  :user_name,  :name_id)
    end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= simple_form_for(@notification) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<style type="text/css">
  .links-on-notifications {
    position: relative;
    bottom: 16px;
    left: 40px;

  }
  .card-icon-outline-success {
   border: 1px solid rgba(76, 175, 80, 0.6);
   background: rgba(76, 175, 80, 0.6)!important;
   }
  .card-1-color {
   background:  #212529 !important;
   }
</style>
<div class="row ">
   <div class="col-xl-12">

      <div class="card card-1-color  mb-4 p-0 tasks-card">
         <div class="card-header  card-header-icon">
            <%= link_to new_deal_path, class: "text-white", title: 'Click to Add New Deal', rel: "tooltip" do %>
            <div class="card-icon card-icon-outline-success text-white">
               <i class="material-icons">notifications</i>
            </div>
            <% end %>
         </div>
         <div class="card-body mb-4 task-body card-1-color ">
            <div class="tab-content p-0">
               <div class="tab-pane active" id="maindash_tasks">
                  <div class="table-responsive">
                     <table class="table p-0">
                        <tbody class="p-0 m-0" id="task-table-prop-1 card-1 ">
                          <h4 class="text-muted m-2 pb-1 ">All notification</h4>
                          <% notifi_type  = ''%>
                           <% notifi_color = ''%>
                          <% @notifications.each do |notification| %>
                          <% if    notification.thing == 'contact'
                                   notifi_type = 'fa  fa-database'
                                   notifi_color = 'bg-light-info'
                             elsif notification.thing == 'deal'
                                   notifi_type = 'fa fa-suitcase'
                                   notifi_color = 'bg-light-warning'
                             elsif notification.thing == 'task'
                                   notifi_type = 'fa fa-tasks'
                                   notifi_color = 'bg-light-danger'
                             elsif notification.thing == 'lead'
                                   notifi_type = 'fa fa-bolt'
                                   notifi_color = 'bg-light-inverse'
                            elsif  notification.thing == 'issue'
                                   notifi_type = 'fa fa-exclamation-triangle'
                                   notifi_color = 'bg-light-danger'
                             end
                          %>
                          <% user =  User.find(notification.name_id) if notification.name_id %>
                          <tr>
                             <tr> <% class_str = "btn btn-just-icon  btn-round "+  notifi_color %>
                             <td> <%= link_to notification_path(notification.id), class: class_str  do %>

                             <i class="<%="#{notifi_type}"%>"></i><div class="ripple-container"></div></button><% end %></td><td class="text-right"><%= notification.name %> | <%= link_to user_path(user.id), class: "text-info" do user.first_name end %> | <span class="text-warning "> for <% notification.users.each do |user|%> <%= user.first_name %> <%end %></span>  </span><span class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</span> <span><%= link_to notification_path(notification.id), remote: true, method: :delete, data: { confirm: 'Are you sure?', AuthenticityToken: form_authenticity_token}, class: "text-danger", rel: 'tooltip', title: 'Delete' do %>
                      <i class="material-icons text-danger">delete</i>
                   <% end %></span>
                 </h6></td>
                          </tr>
                          <% end %>

                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </div>
  </div>
  <br>
    <span class="links-on-notifications"><%= link_to 'Delete all notifications',all_users_notifications_path, class: "text-danger" %></span>

app/views/notifications/new.html.erb
<h1>New Notification</h1>

<%= render 'form', notification: @notification %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<%  notification = @notification %>
<style type="text/css">
  .links-on-notifications {
    position: relative;
    bottom: 16px;
    left: 40px;

  }
</style>
<div class="row ">
   <div class="col-xl-6">
      <div class="card card-1  mb-4 p-0 tasks-card">
         <div class="card-header  card-header-icon">
            <%= link_to new_notification_path, class: "text-white", title: 'Click to Add New Deal', rel: "tooltip" do %>
            <div class="card-icon bg-black">
               <i class="material-icons">notifications</i>
            </div>
            <% end %>
         </div>
         <div class="card-body mb-4 task-body card-1 ">
            <div class="tab-content p-0">
               <div class="tab-pane active" id="maindash_tasks">
                  <div class="table-responsive">
                     <table class="table p-0">
                        <tbody class="p-0 m-0" id="task-table-prop-1 card-1 ">
                          <h4 class="text-muted m-2 pb-1 ">All notification</h4>
                          <% notifi_type  = '' %>
                           <% notifi_color = '' %>

                          <% if    notification.thing == 'contact'
                                   notifi_type = 'fa  fa-database'
                                   notifi_color = 'bg-info'
                             elsif notification.thing == 'deal'
                                   notifi_type = 'fa fa-suitcase'
                                   notifi_color = 'bg-warning'
                             elsif notification.thing == 'task'
                                   notifi_type = 'fa fa-tasks'
                                   notifi_color = 'bg-danger'
                             elsif notification.thing == 'lead'
                                   notifi_type = 'fa fa-bolt'
                                   notifi_color = 'bg-inverse'
                            elsif  notification.thing == 'issue'
                                   notifi_type = 'fa fa-exclamation-triangle'
                                   notifi_color = 'bg-danger'
                             end
                          %>
                          <% user =  User.find(notification.name_id) %>
                          <tr>
                             <tr> <% class_str = "btn btn-just-icon  btn-round "+  notifi_color %>
                             <td> <%= link_to notification_path(notification), class: class_str  do %>

                             <i class="<%="#{notifi_type}"%>"></i><div class="ripple-container"></div></button><% end %></td><td class="text-right"><%= notification.name %> | <%= link_to user_path(user.id), class: "text-info" do user.first_name end %> | <span class="text-muted"><%= time_ago_in_words(notification.created_at) %> ago</span> <span><%= link_to notification_path, remote: true, method: :delete, data: { confirm: 'Are you sure?', AuthenticityToken: form_authenticity_token}, class: "text-danger", rel: 'tooltip', title: 'Delete' do %>
                      <i class="material-icons text-danger">delete</i>
                   <% end %></span>
                 </h6></td>
                          </tr>


                        </tbody>
                     </table>
                  </div>
               </div>
            </div>
         </div>
      </div>
    </div>
  </div>
  <br>





                          <%

                                   subject = ''
                             if    @notification.thing == 'contact'
                                   if  @notification.thing_id and Contact.find(@notification.thing_id)
                                      @subject_object = Contact.find(@notification.thing_id)
                                      subject = 'Contact'
                                   end
                                   notifi_type = 'fa  fa-database'
                                   notifi_color = 'bg-light-info'
                             elsif @notification.thing == 'deal'
                                   if  @notification.thing_id and Deal.find(@notification.thing_id)
                                     @subject_object = Deal.find(@notification.thing_id)
                                     subject = 'Deal'
                                   end
                                   notifi_type = 'fa fa-suitcase'
                                   notifi_color = 'bg-light-warning'
                             elsif @notification.thing == 'task'
                                   notifi_type = 'fa fa-tasks'
                                   notifi_color = 'bg-light-danger'
                                   @subject_object = Task.find(@notification.thing_id)
                             elsif @notification.thing == 'lead'
                                   @subject_object = Lead.find(@notification.thing_id)
                                   subject = 'Lead'
                                   notifi_type = 'fa fa-bolt'
                                   notifi_color = 'bg-light-inverse'
                            elsif  @notification.thing == 'issue'
                                   @subject_object = Issue.find(@notification.thing_id)
                                   subject = 'Issue'
                                   notifi_type = 'fa fa-exclamation-triangle'
                                   notifi_color = 'bg-light-danger'
                                   @subject_object = Issue.find(@notification.thing_id)
                                   subject = 'Issue'
                                   notifi_type = 'fa fa-calendar'
                                   notifi_color = 'bg-light-inverse'
                            elsif  @notification.thing == 'post'
                                   @subject_object = Mainpost.find(@notification.thing_id)
                                   subject = 'post'
                                   notifi_type = 'fa fa-comment'
                                   notifi_color = 'bg-light-info'
                           elsif  @notification.thing == 'company'
                                   notifi_type = 'fa fa-building'
                                   notifi_color = 'bg-light-info'
                           end

                          %>



                           <%  if subject == 'Contact' %>
                             <p> Contact Name:      <%= link_to contact_path(@subject_object), class: 'text-info' do %> <%=@subject_object.name %><% end %></p>
                             <p> Contact Company: <%= @subject_object.company %></p>
                             <p> Contact: Email: <%= @subject_object.email %></p>
                            <% elsif subject == 'Deal' %>
                             <p> Deal Name:      <%= link_to deal_path(@subject_object), class: 'text-info' do %> <%=@subject_object.name %><% end %></p>
                             <p> Deal Contacts: <%= @subject_object.contacts.each do |contact| %><%= contact.name %>&nbsp;<% end %></p>
                             <p> Deal Contacts: <%= @subject_object.status %></p>
                             <% end %>
<%= link_to 'Edit', edit_notification_path(@notification), class: 'text-white' %> |
<%= link_to 'Back', notifications_path, class: 'text-white' %>