config/routes.rb
  Rails.application.routes.draw do

  resources :owners
  resources :tenants
  resources :categories
  resources :marketings
  resources :steps
  resources :letters do
       post 'basic_letter', on: :collection
       post 'cover_letter', on: :collection
       post 'proposal_purchase', on: :collection
       post 'proposal_lease', on: :collection
       post 'exclusive_agreement', on: :collection
       post 'beechwood_letter', on: :collection
     end
  resources :notifications do
       get 'just_user', on: :collection
       get 'all_users', on: :collection
     end
  resources :invoices
  resources :maps do
     post "place", on: :collection
     get "places", on: :collection
  end

  resources :appointments
  resources :searcheds
  resources :canvas

  resources :addresses do
      get 'autocomplete', on: :collection
    end

  resources :mainposts
  resources :comments
  resources :likes

  root to: 'visitors#index'
  match "about" => "pages#about", as: :about, via: :get


  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }, :controllers => { registrations: 'registrations', confirmations: 'confirmations'}
    resources :personal_messages, only: [:create, :new]
    resources :conversations, only: [:index, :show]
    resources :users

    resources :groups do
      get 'autocomplete', on: :collection
    end

    resources :tasks
    resources :companies
    resources :events do
    get 'destroy_all', on: :collection
    end

    resources :recurring_events
    resources :projects do
       get 'resources', on: :collection
       get 'description', on: :collection
       get 'budget', on: :collection
       get 'requirements', on: :collection
       get 'projected_start_time', on: :collection
       get 'actual_finshed_time', on: :collection
       get 'development', on: :collection
       get 'maintenance', on: :collection
       get 'technology', on: :collection
       get 'business', on: :collection
       get 'autocomplete', on: :collection
    end

    resources :touches
    resources :leads
    resources :deals do
      resources :posts
      resources :issues
      resources :comments
      get 'autocomplete', on: :collection
    end

    match "users/settheme" => "users#set_theme", as: :set_theme, via: :get
    match "users/sharegroups" => "users#sharegroups", as: :sharegroups, via: :post
    match "search" => "search#create", as: :searches, via: [:get, :post]
    match "search/prepare" => "search#prepare", as: :prepareshearch, via: :get
    match "/dashboard/searchcontacts/" => "dashboard#contacts_search", as: :dash_contacts_search, via: :get
    match "touches/contact/:id" => "touches#contact", as: :contact_touches, via: [:get, :post]

    get '/dashboard', to: 'dashboard#index'

    resources :properties do
     get 'category', on: :collection
     get 'search', on: :collection
     resources :posts
     resources :issues
     get 'autocomplete', on: :collection
    end

    resources :contacts do
      get 'autocomplete', on: :collection
      get 'searchname', on: :collection
      post 'inport', on: :collection
      get 'letter'=> 'contacts#letter'
    end

  end

app/models/group.rb
class Group < ApplicationRecord
  require 'roo'
  require 'csv'
   has_and_belongs_to_many :contacts
   has_and_belongs_to_many :users
   has_and_belongs_to_many :tasks
   has_and_belongs_to_many :categories


   validates :name, presence: true
   validates :name, uniqueness: true

  def self.search(term)
    where('name LIKE ? ', "%#{term}%") if term.present?
  end

 def to_csv(contacts, options = {})
  CSV.generate(options) do |csv|

      header = {
  :id=> "Id",
  :name=> "Name",
 :prefix=> "Prefix",
 :first_name=> "First Name",
 :middle_name=> "Middle Name",
 :last_name=> "Last Name",
 :suffix=> "Suffix",
 :postion=> "Position",
 :web_address=> "Web Address",
 :latitude=> "Latitude",
 :longitude=> "Longitude",
 :facility_size=> "Facility Size",
 :total_number_of_employees=> "Total Number Of Employees",
 :primary_industry=> "Primary Industry",
 :year_of_Founding=>  "Year Of Founding",
 :owns_cents=> "Owns Rents",
 :email=> "Email",
 :company=>  "Company",
 :phone=>  "Phone",
 :Fulladdress=>  "Full Address",
 :street_num => "Street Number",
 :strret_name => "Street Name",
 :city=> "City",
 :state=> "State",
 :county=> "County",
 :country=> "Country",
 :postal_code=> "Postal Code",
 :zip_code_ext=> "Zip Code Ext"
}
    csv << header.values
    contacts.each do |contact|

      h = {
 :id=> contact.id.to_s,
 :name=> contact.name.to_s,
 :prefix=> contact.prefix.to_s,
 :first_name=> contact.first_name.to_s,
 :middle_name=> contact.middle_name.to_s,
 :last_name=> contact.last_name.to_s,
 :suffix=> contact.suffix.to_s,
 :postion=> contact.postion.to_s,
 :web_address=> contact.web_address.to_s,
 :latitude=>contact.latitude.to_s,
 :longitude=> contact.longitude.to_s,
 :facility_size=>contact.facility_size,
 :total_number_of_employees=>contact.total_number_of_employees.to_s,
 :primary_industry=>contact.primary_industry.to_s,
 :year_of_Founding=> contact.year_of_Founding.to_s,
 :owns_cents=>contact.owns_cents.to_s,
 :email=> contact.email.to_s,
 :company=> contact.company.to_s,
 :phone=> contact.phone.to_s,
 :Fulladdress=> contact.Fulladdress.to_s,
 :street_num=>contact.street_num.to_s,
 :strret_name=>contact.strret_name.to_s,
 :city=> contact.city.to_s,
 :state=> contact.state.to_s,
 :county=>contact.county.to_s,
 :country=> contact.country.to_s,
 :postal_code=>contact.postal_code.to_s,
  :zip_code_ext=> contact.zip_code_ext.to_s
}
       csv << h.values

    end
  end
end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  require "csv"
  require 'roo'
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all.order(:name)
       respond_to do |format|
        format.html
        format.js
      end
  end

  def autocomplete
       @groups = Group.search(params[:term])
  end

  def show
    session[:return_to] = request.referer
    respond_to do |format|
    format.html
    format.csv { send_data @group.to_csv(@group.contacts) }
    format.xls
    format.js
    end
  end

  def new
    @group = Group.new
    @users = User.all
  end

  def edit

  end

  def create
   @group = Group.new(group_params)
    if @group.save
      flash[:info] = "Group with the slected users was successfully created."
     render json: @group, status: :created
    end
  end

  def update
     if  @group.update(group_params)
          flash[:info] = "Group with the slected users was successfully updated."
            @groups = Group.all.order(:name)
    render action: "index"
    else
       flash[:danger] = @group.errors.full_messages.to_s
        render action: "edit"
    end
  end

  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end
  def group_params
    params.require(:group).permit(:name, :id, :touch_ids, :contact_id => [], :user_ids => [])
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_edit.html.erb
<div id="main-wrap">
   <div class="container" >
      <div class="col-md-6 mr-auto ml-auto p-4">
         <div class="row ">
            <div class="col-md-8">
               <h1 class="pull-left">Editing Group</h1>
            </div>
            <div class="col-md-4">
            <span class="text-info float-right mt-4 pt-4">
               <%= link_to 'Show', @group, class: 'text-info' %> | <%= link_to 'Back', groups_path, class: 'text-info' %>
            </span>
            </div>
            </div>
            <%= render 'form', group: @group %>
         </div>
      </div>
   </div>

app/views/groups/_group.html.erb
<div class="col-md-12">
   <% @groups.each.each_slice(3) do |group| %>
   <div class="col-md-12 mb-3">
      <div class="row">
         <% group.each do |group| %>
         <div class=" col-md-4 ">
            <div class="card card-raised  card-1-color group-card" >
               <div class="card-body">
                  <h2 class="card-category text-white"><%= group.name %> <span class="pull-right text-hudson"><%= group.contacts.count %></span>
                     </h2>
                  <a href="#pablo">
                     <h4 class="card-title">Download:<%= link_to " CSV", group_path(group.id, format: "csv"), class: 'text-danger' %></h4>
                  </a>
                  <p class="card-description">
                     <%= group.name %> has <%= group.contacts.count %> contact stored
                  </p>
                 <h6> <%= link_to group_path(group.id), class: "btn btn-outline-white text-white btn-round group-view-link", remote: true do %>
                  <i class="material-icons">content_copy</i> View Group
                  <% end %>
                  <span class="pull-right delete-group-link"> <%= link_to group, remote: true, method: :delete, data: { confirm: 'Are you sure?', AuthenticityToken: form_authenticity_token}, class: "text-danger delete_group", rel: 'tooltip', title: 'Delete' do %>
                      <i class="material-icons text-danger">delete</i>
                   <% end %></span>
                 </h6>
               </div>
            </div>
         </div>
         <% end %>
      </div>
      <hr class="bg-light">
   </div>
   <% end %>
</div>

app/views/groups/_index.html.erb
<div id="main-wrap">
   <p id="notice"><%= notice %></p>
   <div class="container-fluid">
   </div>
   <div id="groups">
      <div class="container-fluid   card-1 pt-4 first-show-card">

         <div class="m-4">
             <%= link_to new_group_path, class: "text-white" do %>
           <span class="pull-right mt-2"><i class="fa fa-plus"></i> New</span>
           <% end %>

            <span >
               <% @groups.each_with_index do |g, i| %>
               <%= link_to group_path(g.id) do %>
               <span class="badge rounded-0 card-1-colo m-2 pt-3">
                  <h5><%= g.name %></h5>
               </span>
            </span>
            <% end %>
            <% end %>
         </div>
         <div class="bs-example first-show-card">
            <div class="list-group outer-list" id="render-groups">
               <%= render  'group' %>
            </div>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="col-md-8 mr-auto ml-auto">
         <div class="modal-body" id="form-modal-body"></div>
      </div>
   </div>
</div>

app/views/groups/_show.html.erb
<div class="col-md-12">
   <div class="">
      <div class="collapse" id="contacts-header">
         <div class="row">
            <div class="col-md-8">
               <h2>
                  <span><%= @group.name %> <%= link_to  edit_group_path(@group), remote: true, class: 'btn btn-just-icon btn-round mdl-color--grey-900 ml-3' do %>
                  <i class="fa fa-edit"></i>
                  <% end %>
                   <span class="pull-right delete-group-link"> <%= link_to @group, method: :delete, data: { confirm: 'Are you sure?', AuthenticityToken: form_authenticity_token}, class: "text-danger delete_group", rel: 'tooltip', title: 'Delete' do %>
                      <i class="material-icons text-danger">delete</i>
                   <% end %></span>

                  <span class="ml-4 pl-3">
                  <%= link_to  group_path(@group.id, format: "csv"), class: 'btn mdl-color--grey-900  btn-left-margin' do %>
                  <i class="fa fa-file-text"></i> Download Excel/CSV
                  <% end %>
                  </span>
                  </span>
               </h2>
            </div>
            <div class="col-md-4">
               <form action="/contacts/" id="user-search" class="well form-inline pull-right" method="get" accept-charset="utf-8">
                  <div style="display:none;"><input type="hidden" name="group_id" value=<%= "#{@group.id}" %>></div>
                  <input name="term" class="form-control" placeholder="Search this group" id="search" autocomplete="off" type="text">
                  <button type="submit" class="btn mdl-color--grey-900 btn-round btn-just-icon mr-3" id="send-search">
                     <i class="material-icons">search</i>
                     <div class="ripple-container"></div>
                  </button>
               </form>
            </div>
            <div class="col-md-12">
               <div class="filter-box" style="display:none;">
                  <% delete_string =  "Delete " + @group.name %>
                  <div class="col-lg-11 mr-auto ml-auto">
                     <h3 class=" pl-2">  <span> <%= @group.name %> / <%= @group.contacts.count %> <% edit_string =  "Edit " + @group.name %> <%= link_to edit_group_path(@group.id), class: "btn btn-link remote-link btn-success text-success", remote: true, title: edit_string, rel: "tooltip"  do %>
                        <i class=" fa fa-edit e-contact pb-4 mb-3"></i>    <% end %></span><span class="pull-right" > <span class="pull-right ">   <%= link_to @group, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger pr-4", remote: true, title: delete_string, rel: "tooltip" do %>
                        <i class="material-icons text-danger pt-4">delete</i>
                        <% end %></span>  <button type="button" class="btn-back btn btn-link text-white pt-4"><i class="material-icons">keyboard_backspace</i></button> </span></strong>
                     </h3>
                  </div>
               </div>
               <div class="col-md-12">
               </div>
            </div>
         </div>
      </div>
      <div class="card card-1-color rounded-0 pt-3">
         <div class="card-header card-header-icon">
            <div class="card-icon bg-hudson">
               <i class="material-icons">group</i>
            </div>
            <h4 class="card-title text-white"><%= @group.name %>
               <span>
               <a class="btn-link text-white pull-right  pt-0" data-toggle="collapse" href="#contacts-header" aria-expanded="false" aria-controls="contacts-header">
               <i class="material-icons">whatshot</i>
               </a>
               </span>
            </h4>
         </div>
         <div class="card-body">
            <div class="table-responsive">
               <table class="table">
                  <thead class="">
                     <tr>

                        <th class="d- text-info">Edit </th>
                        <th class="d- text-info">Name </th>
                        <th class="d- text-info">suffix </th>
                        <th class="d- text-info">position</th>
                        <th class="d- text-info">company </th>
                        <th class="d- text-info">full address </th>
                        <th class="d- text-info">street #</th>
                        <th class="d- text-info">street name </th>
                        <th class="d- text-info">suite </th>
                        <th class="d- text-info">city </th>
                        <th class="d- text-info">state </th>
                        <th class="d- text-info">postal code </th>
                        <th class="d- text-info">zipcode ext</th>
                        <th class="d- text-info">county</th>
                        <th class="d- text-info">phone</th>
                        <th class="d- text-info">cellphone</th>
                        <th class="d- text-info">email</th>
                        <th class="d- text-info">webaddress </th>
                        <th class="d- text-info">facility size </th>
                        <th class="d- text-info">total employees </th>
                        <th class="d- text-info">prefix </th>
                        <th class="d- text-info">first name</th>
                        <th class="d- text-info">middle name  </th>
                        <th class="d- text-info">last name </th>
                        <th class="d- text-info">Owns or Rents</th>
                        <th class="d- text-info">lattitude</th>
                        <th class="d- text-info">lattitude </th>
                        <th class="d- text-info">primary industry</th>
                        <th class="d- text-info">sic </th>
                        <th class="d- text-info">country </th>

                     </tr>
                  </thead>

                  <tbody>
                     <%  @group.contacts.order(:last_name).each do |contact| %>
                     <tr>
                        <td class="text-white">
                           <%= link_to  edit_contact_path(contact), remote: true do %><i class="fa fa-edit"></i><% end %>
                        </td>
                        <td class="d-">
                           <%= link_to contact_path(contact.id), class: "text-white", title: 'view profile', rel: "tooltip"  do %>
                           <%= contact.name %>
                           <% end %>
                        </td>
                        <td class="d-"><%= contact.suffix %></td>
                        <td class="d-"><%= contact.postion %></td>
                        <td class="d-"><%= contact.company %></td>
                        <td class="d-"><%= contact.Fulladdress %></td>
                        <td class="d-"><%= contact.street_num %></td>
                        <td class="d-"><%= contact.strret_name %></td>
                        <td class="d-"><%= contact.suite %></td>
                        <td class="d-"><%= contact.city %></td>
                        <td class="d-"><%= contact.state %></td>
                        <td class="d-"><%= contact.postal_code %></td>
                        <td class="d-"><%= contact.zip_code_ext %></td>
                        <td class="d-"><%= contact.county %></td>
                        <td class="d-"><%= contact.phone %></td>
                        <td class="d-"><%= contact.cell %></td>
                        <td class="d-"><%= contact.email %></td>
                        <td class="d-"><%= contact.web_address %></td>
                        <td class="d-"><%= contact.facility_size %></td>
                        <td class="d-"><%= contact.total_number_of_employees %></td>
                        <td class="d-"><%= contact.prefix %></td>
                        <td class="d-"><%= contact.first_name %></td>
                        <td class="d-"><%= contact.middle_name %></td>
                        <td class="d-"><%= contact.last_name %></td>
                        <td class="d-"><%= contact.owns_cents %></td>
                        <td class="d-"><%= contact.latitude %></td>
                        <td class="d-"><%= contact.latitude %></td>
                        <td class="d-"><%= contact.primary_industry %></td>
                        <td class="d-"><%= contact.sic %></td>
                        <td class="d-"><%= contact.country %></td>
                     </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>

app/views/groups/destroy.js.erb
$('.delete_group').bind('ajax:success', function() {
   $(this).closest('.group-card').fadeOut();
});

app/views/groups/edit.html.erb
<div id="main-wrap">
   <div class="container" >
      <div class="col-md-6 mr-auto ml-auto p-4">
         <div class="row ">
            <div class="col-md-8">
               <h1 class="pull-left">Editing Group</h1>
            </div>
            <div class="col-md-4">
            <span class="text-info float-right mt-4 pt-4">
               <%= link_to 'Show', @group, class: 'text-info' %> | <%= link_to 'Back', groups_path, class: 'text-info' %>
            </span>
            </div>
         </div>
         <%= render 'form', group: @group %>
      </div>
   </div>
</div>

app/views/groups/edit.js.erb
$('#main-content').html('<%= escape_javascript render("groups/edit") %>');
$('.select_u_picker').selectpicker('val', '<%= @users.to_s %>').selectpicker('setStyle', 'btn-outline-info');
$('.select_u_picker').attr("data-actions-box", "true");
$('.select_u_picker').selectpicker('selectAll');
$('.select_u_picker').attr("dropupAuto", "false");
$('.select_u_picker').attr("selectOnTabr", "true");
$('.select_u_picker').attr("data-divider", "true");
$('.selectpicker').selectpicker('toggle');

app/views/groups/index.html.erb
<div id="main-wrap">
   <p id="notice"><%= notice %></p>
   <div class="container-fluid">
   </div>
   <div id="groups">
      <div class="container-fluid   card-1 pt-4 first-show-card">

         <div class="m-4">
             <%= link_to new_group_path, class: "text-white" do %>
           <span class="pull-right mt-2"><i class="fa fa-plus"></i> New</span>
           <% end %>

            <span >
               <% @groups.each_with_index do |g, i| %>
               <%= link_to group_path(g.id) do %>
               <span class="badge rounded-0 card-1-color m-2 pt-3">
                  <h5><%= g.name %></h5>
               </span>
            </span>
            <% end %>
            <% end %>
         </div>
         <div class="bs-example first-show-card">
            <div class="list-group outer-list" id="render-groups">
               <%= render  'group' %>
            </div>
         </div>
      </div>
   </div>
   <div class="container">
      <div class="col-md-8 mr-auto ml-auto">
         <div class="modal-body" id="form-modal-body"></div>
      </div>
   </div>
</div>

app/views/groups/index.js.erb
$('#main-content').html('<%= escape_javascript render("groups/index") %>');

app/views/groups/new.html.erb
<div id="main-wrap">
   <div class="container" >
      <div class="col-md-6 mr-auto ml-auto p-4">
         <div class="row ">
            <div class="col-md-8">
               <h1 class="pull-left">New Group</h1>
            </div>
            <div class="col-md-4">
               <%= link_to 'Back', groups_path, class: 'text-info float-right mt-4 pt-4' %>
            </div>

            </div>
            <%= render 'form', group: @group %>
         </div>
      </div>
   </div>
</div>

app/views/groups/new.js.erb.js.erb
$('#main-wrap').html('<%= escape_javascript render("groups/new") %>');

$('.select_u_picker').selectpicker('val', '<%= @users.to_s %>').selectpicker('setStyle', 'btn-outline-info');

app/views/groups/show.html.erb
<div class="col-md-12">
   <div class="">
      <div class="collapse" id="contacts-header">
         <div class="row">
            <div class="col-md-8">
               <h2>
                  <span><%= @group.name %> <%= link_to  edit_group_path(@group), remote: true, class: 'btn btn-just-icon btn-round mdl-color--grey-900 ml-3' do %>
                  <i class="fa fa-edit"></i>
                  <% end %>
                   <span class="pull-right delete-group-link"> <%= link_to @group, method: :delete, data: { confirm: 'Are you sure?', AuthenticityToken: form_authenticity_token}, class: "text-danger delete_group", rel: 'tooltip', title: 'Delete' do %>
                      <i class="material-icons text-danger">delete</i>
                   <% end %></span>

                  <span class="ml-4 pl-3">
                  <%= link_to  group_path(@group.id, format: "csv"), class: 'btn mdl-color--grey-900  btn-left-margin' do %>
                  <i class="fa fa-file-text"></i> Download Excel/CSV
                  <% end %>
                  </span>
                  </span>
               </h2>
            </div>
            <div class="col-md-4">
               <form action="/contacts/" id="user-search" class="well form-inline pull-right" method="get" accept-charset="utf-8">
                  <div style="display:none;"><input type="hidden" name="group_id" value=<%= "#{@group.id}" %>></div>
                  <input name="term" class="form-control" placeholder="Search this group" id="search" autocomplete="off" type="text">
                  <button type="submit" class="btn mdl-color--grey-900 btn-round btn-just-icon mr-3" id="send-search">
                     <i class="material-icons">search</i>
                     <div class="ripple-container"></div>
                  </button>
               </form>
            </div>
            <div class="col-md-12">
               <div class="filter-box" style="display:none;">
                  <% delete_string =  "Delete " + @group.name %>
                  <div class="col-lg-11 mr-auto ml-auto">
                     <h3 class=" pl-2">  <span> <%= @group.name %> / <%= @group.contacts.count %> <% edit_string =  "Edit " + @group.name %> <%= link_to edit_group_path(@group.id), class: "btn btn-link remote-link btn-success text-success", remote: true, title: edit_string, rel: "tooltip"  do %>
                        <i class=" fa fa-edit e-contact pb-4 mb-3"></i>    <% end %></span><span class="pull-right" > <span class="pull-right ">   <%= link_to @group, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-danger pr-4", remote: true, title: delete_string, rel: "tooltip" do %>
                        <i class="material-icons text-danger pt-4">delete</i>
                        <% end %></span>  <button type="button" class="btn-back btn btn-link text-white pt-4"><i class="material-icons">keyboard_backspace</i></button> </span></strong>
                     </h3>
                  </div>
               </div>
               <div class="col-md-12">
               </div>
            </div>
         </div>
      </div>
      <div class="card card-1-color rounded-0 pt-3">
         <div class="card-header card-header-icon">
            <div class="card-icon bg-hudson">
               <i class="material-icons">group</i>
            </div>
            <h4 class="card-title text-white"><%= @group.name %>
               <span>
               <a class="btn-link text-white pull-right  pt-0" data-toggle="collapse" href="#contacts-header" aria-expanded="false" aria-controls="contacts-header">
               <i class="material-icons">whatshot</i>
               </a>
               </span>
            </h4>
         </div>
         <div class="card-body">
            <div class="table-responsive">
               <table class="table">
                  <thead class="">
                     <tr>

                        <th class="d- text-info">Edit </th>
                        <th class="d- text-info">Name </th>
                        <th class="d- text-info">suffix </th>
                        <th class="d- text-info">position</th>
                        <th class="d- text-info">company </th>
                        <th class="d- text-info">full address </th>
                        <th class="d- text-info">street #</th>
                        <th class="d- text-info">street name </th>
                        <th class="d- text-info">suite </th>
                        <th class="d- text-info">city </th>
                        <th class="d- text-info">state </th>
                        <th class="d- text-info">postal code </th>
                        <th class="d- text-info">zipcode ext</th>
                        <th class="d- text-info">county</th>
                        <th class="d- text-info">phone</th>
                        <th class="d- text-info">cellphone</th>
                        <th class="d- text-info">email</th>
                        <th class="d- text-info">webaddress </th>
                        <th class="d- text-info">facility size </th>
                        <th class="d- text-info">total employees </th>
                        <th class="d- text-info">prefix </th>
                        <th class="d- text-info">first name</th>
                        <th class="d- text-info">middle name  </th>
                        <th class="d- text-info">last name </th>
                        <th class="d- text-info">Owns or Rents</th>
                        <th class="d- text-info">lattitude</th>
                        <th class="d- text-info">lattitude </th>
                        <th class="d- text-info">primary industry</th>
                        <th class="d- text-info">sic </th>
                        <th class="d- text-info">country </th>

                     </tr>
                  </thead>

                  <tbody>
                     <%  @group.contacts.order(:last_name).each do |contact| %>
                     <tr>
                        <td class="text-white">
                           <%= link_to  edit_contact_path(contact), remote: true do %><i class="fa fa-edit"></i><% end %>
                        </td>
                        <td class="d-">
                           <%= link_to contact_path(contact.id), class: "text-white", title: 'view profile', rel: "tooltip"  do %>
                           <%= contact.name %>
                           <% end %>
                        </td>
                        <td class="d-"><%= contact.suffix %></td>
                        <td class="d-"><%= contact.postion %></td>
                        <td class="d-"><%= contact.company %></td>
                        <td class="d-"><%= contact.Fulladdress %></td>
                        <td class="d-"><%= contact.street_num %></td>
                        <td class="d-"><%= contact.strret_name %></td>
                        <td class="d-"><%= contact.suite %></td>
                        <td class="d-"><%= contact.city %></td>
                        <td class="d-"><%= contact.state %></td>
                        <td class="d-"><%= contact.postal_code %></td>
                        <td class="d-"><%= contact.zip_code_ext %></td>
                        <td class="d-"><%= contact.county %></td>
                        <td class="d-"><%= contact.phone %></td>
                        <td class="d-"><%= contact.cell %></td>
                        <td class="d-"><%= contact.email %></td>
                        <td class="d-"><%= contact.web_address %></td>
                        <td class="d-"><%= contact.facility_size %></td>
                        <td class="d-"><%= contact.total_number_of_employees %></td>
                        <td class="d-"><%= contact.prefix %></td>
                        <td class="d-"><%= contact.first_name %></td>
                        <td class="d-"><%= contact.middle_name %></td>
                        <td class="d-"><%= contact.last_name %></td>
                        <td class="d-"><%= contact.owns_cents %></td>
                        <td class="d-"><%= contact.latitude %></td>
                        <td class="d-"><%= contact.latitude %></td>
                        <td class="d-"><%= contact.primary_industry %></td>
                        <td class="d-"><%= contact.sic %></td>
                        <td class="d-"><%= contact.country %></td>
                     </tr>
                     <% end %>
                  </tbody>
               </table>
            </div>
         </div>
      </div>
   </div>

app/views/groups/show.js.erb
$('#main-content').html('<%= escape_javascript render("groups/show") %>');